version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: Add apt repo for ffmpeg
          command: |
            apt-get update
            apt-get install -y ffmpeg
      - run: ffmpeg -h
