version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: Add apt repo for ffmpeg
          command: |
            sudo apt-get update
            sudo apt-get install -y ffmpeg
      - run: ffmpeg -h

      - run: sh -c 'groupadd --gid 3434 circleci'
      - run: sh -c 'useradd --uid 3434 --gid circleci --shell /bin/bash --create-home circleci'
      - run: sh -c 'echo "circleci ALL=NOPASSWD: ALL" >> /etc/sudoers.d/50-circleci'
      - run: sh -c 'echo "Defaults    env_keep += 'noninteractive'" >> /etc/sudoers.d/env_keep'
