version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: echo "A first hello"
      - run: uname -a
      - run: cat /etc/issue
      # install ffmpeg
      - run: sudo apt-get install -y software-properties-common
      - run: sudo add-apt-repository ppa:jonathonf/ffmpeg-4
      - run: sudo apt-get update
      - run: sudo apt install -y ffmpeg
      - run: ffmpeg -version

