version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: echo "A first hello"
      # pipenv
      - run: sudo pip install pipenv
      - run: pipenv install -d
