version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0a3       
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: Add apt repo for ffmpeg
          command: |
            sudo apt-get update
            sudo apt-get install -y ffmpeg
      - run: ffmpeg -h
