version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: echo "A first hello"
      - run: uname -a
      - run: cat /etc/issue
      # install ffmpeg
      #- run: sudo sh -c 'echo "deb http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu bionic main" >> /etc/apt/sources.list'
      - run: sudo apt-get install -y software-properties-common
      - run: sudo add-apt-repository ppa:jonathonf/ffmpeg-4
      - run: sudo apt-get update
      - run: sudo apt install gnupg
      - run: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4AB0F789CBA31744CC7DA76A8CF63AD3F06FC659
      - run: sudo apt install ffmpeg && ffmpeg -version
